### PR TITLE
Single connection v2.0 dev

### PR DESCRIPTION
**Pull request by Akamad007**
This is a fix for the following issue. I have tested it on my local machine using celery. It worked fine. 
http://stackoverflow.com/questions/30982717/in-django-send-mass-mail-creates-a-new-http-connection-
everytime-it-sends-a-mail

### CODE REVIEW

**Comment by medmunds** [comment]
Thanks for contributing to Djrill, @Akamad007. This is a nice improvement for large sends.

Two things:

1. Would you mind [squashing](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request) your commits to get rid of "removed build files" and "removed eclipse hidden files"? ([Longer explanation](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit).)

2. This change breaks the tests -- not because your code is wrong, but because the tests are wrong after your change. The issue is that DjrillBackendMockAPITestCase [patches requests.post](https://github.com/brack3t/Djrill/blob/v2.0-dev/djrill/tests/mock_backend.py#L24), but with your change we're now calling requests.Session.post.

**Comment by Akamad007** [comment]
@medmunds Should I change the tests to accommodate "session" ? I have removed the comments.

**Comment by medmunds** [comment]
@Akamad007 it would be great if you could update the tests to use session. Here's how to [run them locally](http://djrill.readthedocs.org/en/v2.0-dev/contributing/#testing) (you may need to install mock and six). If you run into any problems with it or it starts to become too much work, just let me know and I'm happy to figure it out.

Also, it looks like your build files and eclipse hidden files have reappeared in this pull request (check the "files changed" tab). We actually _don't_ want those -- we only want the changes you made to the Djrill backend. But we want it all to show up as a single commit (check the "commits" tab). You can fix that by "squashing" your three earlier commits into one with git-rebase. (The links my earlier comment show how. Sorry if I wasn't clear about that.)

**Comment by Akamad007** [comment]
@medmunds  I am currently working on the tests part. It is taking more time than expected as I am new to mock. I will keep you updated regarding this. If I am unable to do it, I will let you know. Thanks :)

**Comment by medmunds** [comment]
Covered by #98

**Pull request closed without merging**
